- name: Install dependencies
  become: yes
  apt:
    name: apt-transport-https

- name: Add gitlab apt key
  become: true
  apt_key:
    url: https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey

- name: Add gitlab sources
  become: true
  apt_repository:
    repo: 'deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ bionic main'

- name: Refresh apt cache
  become: true
  apt:
    update_cache: yes

- name: Install the gitlab-ce package
  become: yes
  apt:
    name: gitlab-ce

- name: Copy gitlab configurations
  become: true
  template:
    src: ../files/gitlab.rb
    dest: /etc/gitlab

- name: Reload gitlab configurations
  become: true
  shell: gitlab-ctl reconfigure
