- name: Setting locale to en_US.UTF-8 for the user
  lineinfile:
    path: "/home/{{ ansible_user }}/.profile"
    line: "LC_ALL=en_US.UTF-8"
  environment:
    LC_ALL: en_US.UTF-8

- name: Setting locale to en_US.UTF-8 for the system
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Update apt cache list
  become: true
  apt:
    update_cache: yes

- name: Upgrade all packages
  become: true
  apt:
    upgrade: dist
